version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '5444:5444'
    env_file: .env
    restart: always
  db:
    image: postgres
    volumes:
      - ./aida:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5432:5432'
    restart: always

#version: '3.9'
#services:
#  web:
#    build: .
#    volumes:
#      - ./:app
#    ports:
#      - '5444:5444'
#    container_name: web-app
#    depends_on:
#      - db
#    networks:
#      - postgres
#  db:
#    image: postgres
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    container_name: pg-data
#    env_file: ./.env
#    ports:
#      - '5432:5432'
#    networks:
#      - postgres
#volumes:
#  pgdata:
#networks:
#  postgres:
#    driver: bridge